{ ... }:
{
  imports = [
    home/android-studio/default.nix
    home/corectrl/default.nix
    home/firefox/default.nix
    home/gnome-calendar/default.nix
    home/gnome-feeds/default.nix
    home/home-manager/default.nix
    home/kdenlive/default.nix
    home/minecraft/default.nix
    home/neovim/default.nix
    home/signal-desktop/default.nix
    home/teams/default.nix
    home/wireshark/default.nix
    home/zed/default.nix
    home/zulip/default.nix

    nixos/bacon/default.nix
    nixos/bat/default.nix
    nixos/cargo/default.nix
    nixos/cli-tools/default.nix
    nixos/cli-tools/parallel-disk-usage/default.nix
    nixos/desktop-environment/default.nix
    nixos/discord/default.nix
    nixos/docker/default.nix
    nixos/dprint/default.nix
    nixos/finance/default.nix
    nixos/fish/default.nix
    nixos/fonts/default.nix
    nixos/gimp/default.nix
    nixos/git/default.nix
    nixos/gnupg/default.nix
    nixos/keepassxc/default.nix
    nixos/language-servers/default.nix
    nixos/libreoffice/default.nix
    nixos/localization/default.nix
    nixos/login/default.nix
    nixos/obsidian/default.nix
    nixos/photoqt/default.nix
    nixos/prek/default.nix
    nixos/printing/default.nix
    nixos/qalculate-qt/default.nix
    nixos/sound/default.nix
    nixos/sound-engineering/default.nix
    nixos/spotify/default.nix
    nixos/starship/default.nix
    nixos/steam/default.nix
    nixos/taskwarrior/default.nix
    nixos/thunderbird/default.nix
    nixos/tuifeed/default.nix
    nixos/vlc/default.nix
    nixos/wezterm/default.nix
    nixos/wild/default.nix
    nixos/zellij/default.nix
    nixos/zoom-us/default.nix
  ];
}
