[[language]]
language-servers = ["vscode-json-language-server"]
name = "json"

[[language]]
language-servers = ["vscode-html-languageserver"]
name = "html"

[[language]]
language-servers = ["vscode-css-languageserver"]
name = "css"

[[language]]
auto-format = true
language-servers = ["nil"]
name = "nix"

[language.formatter]
command = "nixfmt"

[language-server]
[language-server.vscode-css-languageserver]
command = "css-languageserver"

[language-server.vscode-html-languageserver]
command = "html-languageserver"

[language-server.vscode-json-language-server]
command = "vscode-json-languageserver"
