attribute = "yellow"
constant = "peach"
"constant.character" = "teal"
"constant.character.escape" = "pink"
constructor = "sapphire"
"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus" = "green"
error = "red"
function = "blue"
"function.macro" = "mauve"
hint = "teal"
info = "sky"
keyword = "mauve"
label = "sapphire"
"markup.heading.1" = "lavender"
"markup.heading.2" = "mauve"
"markup.heading.3" = "green"
"markup.heading.4" = "yellow"
"markup.heading.5" = "pink"
"markup.heading.6" = "teal"
"markup.link.text" = "blue"
"markup.list" = "mauve"
"markup.raw" = "flamingo"
operator = "sky"
punctuation = "overlay2"
"punctuation.special" = "sky"
special = "blue"
string = "green"
"string.regexp" = "pink"
"string.special" = "blue"
"string.special.symbol" = "red"
tag = "blue"
type = "yellow"
"type.enum.variant" = "teal"
"ui.text" = "text"
"ui.virtual" = "overlay0"
"ui.virtual.indent-guide" = "surface0"
variable = "text"
"variable.builtin" = "red"
"variable.other.member" = "teal"
warning = "yellow"

[comment]
fg = "overlay2"

["diagnostic.error".underline]
color = "red"
style = "curl"

["diagnostic.hint".underline]
color = "teal"
style = "curl"

["diagnostic.info".underline]
color = "sky"
style = "curl"

["diagnostic.warning".underline]
color = "yellow"
style = "curl"

["keyword.control.conditional"]
fg = "mauve"

["markup.bold"]
modifiers = ["bold"]

["markup.heading.marker"]
fg = "peach"
modifiers = ["bold"]

["markup.italic"]
modifiers = ["italic"]

["markup.link.url"]
fg = "blue"
modifiers = ["underlined"]

[namespace]
fg = "yellow"

[palette]
base = "#303446"
blue = "#8caaee"
crust = "#232634"
cursorline = "#3b3f52"
flamingo = "#eebebe"
green = "#a6d189"
lavender = "#babbf1"
mantle = "#292c3c"
maroon = "#ea999c"
mauve = "#ca9ee6"
overlay0 = "#737994"
overlay1 = "#838ba7"
overlay2 = "#949cbb"
peach = "#ef9f76"
pink = "#f4b8e4"
red = "#e78284"
rosewater = "#f2d5cf"
sapphire = "#85c1dc"
secondary_cursor = "#b8a5a6"
secondary_cursor_insert = "#83a275"
secondary_cursor_normal = "#9192be"
sky = "#99d1db"
subtext0 = "#a5adce"
subtext1 = "#b5bfe2"
surface0 = "#414559"
surface1 = "#51576d"
surface2 = "#626880"
teal = "#81c8be"
text = "#c6d0f5"
yellow = "#e5c890"

["ui.background"]
bg = "base"
fg = "text"

["ui.bufferline"]
bg = "mantle"
fg = "subtext0"

["ui.bufferline.active"]
bg = "base"
fg = "mauve"

["ui.bufferline.active".underline]
color = "mauve"
style = "line"

["ui.bufferline.background"]
bg = "crust"

["ui.cursor"]
bg = "secondary_cursor"
fg = "base"

["ui.cursor.insert"]
bg = "secondary_cursor_insert"
fg = "base"

["ui.cursor.match"]
fg = "peach"
modifiers = ["bold"]

["ui.cursor.normal"]
bg = "secondary_cursor_normal"
fg = "base"

["ui.cursor.primary"]
bg = "rosewater"
fg = "base"

["ui.cursor.primary.insert"]
bg = "green"
fg = "base"

["ui.cursor.primary.normal"]
bg = "lavender"
fg = "base"

["ui.cursor.primary.select"]
bg = "flamingo"
fg = "base"

["ui.cursor.select"]
bg = "secondary_cursor"
fg = "base"

["ui.cursorline.primary"]
bg = "cursorline"

["ui.help"]
bg = "surface0"
fg = "overlay2"

["ui.highlight"]
bg = "surface1"
modifiers = ["bold"]

["ui.linenr"]
fg = "surface1"

["ui.linenr.selected"]
fg = "lavender"

["ui.menu"]
bg = "surface0"
fg = "overlay2"

["ui.menu.selected"]
bg = "surface1"
fg = "text"
modifiers = ["bold"]

["ui.popup"]
bg = "surface0"
fg = "text"

["ui.selection"]
bg = "surface1"

["ui.statusline"]
bg = "mantle"
fg = "subtext1"

["ui.statusline.inactive"]
bg = "mantle"
fg = "surface2"

["ui.statusline.insert"]
bg = "green"
fg = "base"
modifiers = ["bold"]

["ui.statusline.normal"]
bg = "lavender"
fg = "base"
modifiers = ["bold"]

["ui.statusline.select"]
bg = "flamingo"
fg = "base"
modifiers = ["bold"]

["ui.text.focus"]
bg = "surface0"
fg = "text"
modifiers = ["bold"]

["ui.text.inactive"]
fg = "overlay1"

["ui.virtual.inlay-hint"]
bg = "mantle"
fg = "surface1"

["ui.virtual.jump-label"]
fg = "rosewater"
modifiers = ["bold"]

["ui.virtual.ruler"]
bg = "surface0"

["ui.window"]
fg = "crust"

["variable.parameter"]
fg = "maroon"
